<?php
namespace AppConfig;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-29 at 23:25:47.
 */
class VersionTest extends \PHPUnit_Framework_TestCase
{

   /**
     * @var Version
     */
    protected $ver;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->ver = Version::MAJOR . '.' . Version::MINOR . '.' . Version::PATCH;
    }

    /**
     * @covers LaunchReader\Version::get
     */
    public function testGet()
    {

        $this->assertEquals($this->ver, Version::get());
    }

    /**
     * @covers LaunchReader\Version::getVersion
     */
    public function testGetVersion()
    {
        $this->assertEquals($this->ver, Version::getVersion());
    }

    /**
     * @covers LaunchReader\Version::getMajor
     */
    public function testGetMajor()
    {
        $this->assertEquals(Version::MAJOR, Version::getMajor());
    }

    /**
     * @covers LaunchReader\Version::getMinor
     */
    public function testGetMinor()
    {
        $this->assertEquals(Version::MINOR, Version::getMinor());
    }

    /**
     * @covers LaunchReader\Version::getPatch
     */
    public function testGetPatch()
    {
        $this->assertEquals(Version::PATCH, Version::getPatch());
    }
}
